# Generated by Django 4.1.2 on 2022-10-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='create_time',
            new_name='creation_time',
        ),
    ]
