# Generated by Django 4.1.2 on 2022-11-08 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_rename_create_time_messages_creation_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='chats',
            name='users',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='content',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.AddField(
            model_name='chats',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание чата'),
        ),
        migrations.AddField(
            model_name='chats',
            name='title',
            field=models.CharField(default='Default title', max_length=200, verbose_name='Название чата'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель сообщения'),
        ),
        migrations.AddField(
            model_name='messages',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания сообщения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='message_text',
            field=models.TextField(default='Default mes', verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chats.chats', verbose_name='Чат, в котором находится сообщение'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
