# Generated by Django 4.1.2 on 2022-11-16 16:51

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0003_alter_chats_options_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания чата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chats',
            name='members',
            field=models.ManyToManyField(related_name='chat_user', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
